FROM phpdaily/php:8.0.0-dev-cli-alpine

# System dependencies
RUN apk add --update bash

# Install Composer
RUN wget https://getcomposer.org/composer.phar \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer

# Install Symfony CLI
RUN wget https://get.symfony.com/cli/installer -O - | bash \
    && mv /root/.symfony/bin/symfony /usr/local/bin/symfony
